name: Build Documentation

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04  # More stable than latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-xetex jq

    - name: Collect Markdown Files
      run: |
        mkdir -p docs/en
        # Copy all non-docs markdown files while preserving structure
        find . -name "*.md" -not -path "./docs/*" -exec cp --parents {} docs/en/ \;
        # Flatten structure in docs/en
        find docs/en -name "*.md" -exec mv {} docs/en/ \;
        rm -rf docs/en/*/  # Remove empty directories

    - name: Generate PDFs
      run: |
        mkdir -p docs/pdf
        pandoc docs/en/*.md -o docs/pdf/documentation_en.pdf \
          --pdf-engine=xelatex \
          -V mainfont="DejaVu Sans" \
          -V geometry:margin=1in \
          --toc

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: |
          docs/pdf/*.pdf
          docs/en/
