name: Build Documentation

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04  # More stable than latest
    
    services:
      libretranslate:
        image: libretranslate/libretranslate
        ports:
          - 5000:5000
        options: >-
          --health-cmd "curl -f http://localhost:5000/ || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Setup Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-xetex jq

    - name: Collect Markdown Files
      run: |
        mkdir -p docs/en
        # Copy all non-docs markdown files while preserving structure
        find . -name "*.md" -not -path "./docs/*" -exec cp --parents {} docs/en/ \;
        # Flatten structure in docs/en
        find docs/en -name "*.md" -exec mv {} docs/en/ \;
        rm -rf docs/en/*/  # Remove empty directories

    - name: Translate with LibreTranslate
      timeout-minutes: 10  # Prevent hanging
      run: |
        mkdir -p docs/de
        for file in docs/en/*.md; do
          echo "Translating $file..."
          curl -sSf -X POST "http://localhost:5000/translate" \
            -H "Content-Type: application/json" \
            -d '{
              "q": '"$(jq -Rs . < "$file")"',
              "source": "en",
              "target": "de",
              "format": "text"
            }' | jq -r '.translatedText' > "docs/de/$(basename "$file")"
        done

    - name: Generate PDFs
      run: |
        mkdir -p docs/pdf
        pandoc docs/en/*.md -o docs/pdf/documentation_en.pdf \
          --pdf-engine=xelatex \
          -V mainfont="DejaVu Sans" \
          -V geometry:margin=1in \
          --toc
        
        pandoc docs/de/*.md -o docs/pdf/documentation_de.pdf \
          --pdf-engine=xelatex \
          -V mainfont="DejaVu Sans" \
          -V geometry:margin=1in \
          --toc

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: |
          docs/pdf/*.pdf
          docs/en/
          docs/de/
